AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false
  
Metrics/BlockLength:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false